<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
		<string>key</string>
		<string>inc</string>
		<string>dyn</string>
	</array>
	<key>name</key>
	<string>LS-DYNA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywordpam</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+\.[0-9]+([eE]?[+-]?[0-9]+)?|[+-]?[0-9]+\.[0-9]+([eE]?[+-]?[0-9]+)?|[0-9]+[eE]?[+-]?[0-9]+|[+-]?[0-9]+[eE]?[+-]?[0-9]+|[+-]?[[0-9]+\.]?)</string>
			<key>name</key>
			<string>constant.numeric.float.lsdyna</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))</string>
			<key>name</key>
			<string>constant.numeric.lsdyna</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((\$).*)</string>
		</dict>
		<key>comment2</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((#).*)</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^ *|\G *)((\*).*)</string>
		</dict>
		<key>keywordpam</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.yaml-tmlanguage</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^\w[\w\ ]{5}\/\ )</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lsdyna</string>
	<key>uuid</key>
	<string>570663bf-7744-4575-9fcf-35cde0f23318</string>
</dict>
</plist>
